version: "3.7"
services:
  nginx:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
    volumes:
      - ./:/app

  php-cli:
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./:/app

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: HR-php-test
    ports:
      - "33061:3306"

  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
    volumes:
      - redis:/data

  node:
    image: node:8.6-alpine
    volumes:
      - ./:/app
    working_dir: /app
    tty: true

  mailer:
    image: mailhog/mailhog
    ports:
      - "8081:8025"

volumes:
  mysql:
  redis: