FROM node:13-alpine

RUN apk add --no-cache \
    autoconf \
    automake \
    bash \
    g++ \
    libc6-compat \
    libjpeg \
    libjpeg-turbo-dev \
    libjpeg-turbo-utils \
    libpng-dev \
    make \
    nasm \
    pngquant \
    optipng \
    zlib-dev \
    musl-dev \
    jpeg \
    jpegoptim \
    libtool

WORKDIR /app
